seeds:
- https://canodrom.barcelona/es
- https://www.frauen-gegen-gewalt.de/de/aktuelles.html
- https://www.agenciapresentes.org
priority_urls:
- https://canodrom.barcelona/es
- https://www.cntvalladolid.es/
- https://www.sindicatodeestudiantes.net/index.php/noticias/feminismo-revolucionario/8m-2024-huelga-estudiantil-feminista
- https://ateneodemadrid.com/evento/asufin-8m-2024/
- https://nudmtrieste.noblogs.org/post/2024/02/23/l8-marzo-scendiamo-in-piazza/
- https://www.ayto-caceres.es/noticias/abiertas-las-inscripciones-para-participar-en-la-iii-ruta-senderista-y-carrera-8k-8-motivos-por-la-igualdad-del-ayuntamiento-de-caceres/
- https://lavozdelasierra.es/2024/03/04/celebracion-del-dia-internacional-de-la-mujer-en-torrelodones/
- https://www.grevefeministe.fr/
